---
core:
  num_workers: 20
logging:
  enabled: False
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "hosts.yaml"
    group_file: "groups.yaml"
    defaults_file: "~/nornir_inventory/defaults.yaml"
